[package]
name = "ruraft-types"
version = { workspace = true } 
edition = { workspace = true }
license = { workspace = true }
description = "A placeholder"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
