[package]
name = "ruserf-core"
version = { workspace = true } 
edition = { workspace = true }
license = { workspace = true }
description = "A placeholder"

[features]
default = ["async", "metrics", "async-graphql"]
async = ["showbiz-core/async"]
metrics = ["showbiz-core/metrics"]

async-graphql = ["dep:async-graphql"]

serde = ["dep:serde"]

[dependencies]
atomic = "0.5"
arc-swap = "1.6"
async-lock = "2.7"
async-channel = { version = "1.2" }
async-graphql = { version = "5", optional = true }
agnostic = { workspace = true }
base64 = "0.21"
bitflags = "1"
parking_lot = "0.12"
rand = "0.8"
regex = "1.7"
rmp-serde = { version = "1.1" }
scopeguard = "1"
serde = { workspace = true, optional = true }
serde_json = "1"
smallvec = { version = "1.10", features = ["serde"] }
showbiz-core = { path = "../../showbiz/core", default-features = false }
thiserror = "1"
viewit = "0.1.5"

[dev-dependencies]
tokio = { version = "1.28", features = ["full"] }